# Copyright (c) 2020 GitHub
# Copyright (c) 2024 Imogrify contributors
# File licensed under the MIT license (see build_checks_LICENSE for details).

# Based on: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Build checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ ubuntu-latest, windows-latest ]
        build_type: [ debug, release ]
        compiler: [ gcc, msvc ]
        include:
          - os: ubuntu-latest
            cmake_os: linux
          - os: windows-latest
            cmake_os: windows
        exclude:
          - os: windows-latest
            compiler: gcc
          - os: ubuntu-latest
            compiler: msvc

    steps:
      - uses: actions/checkout@v4

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'
          vcpkgGitCommitId: 'c82f74667287d3dc386bce81e44964370c91a289' # 2024.09.30
          runVcpkgInstall: true
          vcpkgJsonGlob: '**/vcpkg.json'

      - name: Setup ninja
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Configure project
        run: cmake --preset ci-cfg-${{ matrix.cmake_os }}-${{ matrix.build_type }}-${{ matrix.compiler }}

      - name: Build project
        run: cmake --build --preset ci-build-${{ matrix.cmake_os }}-${{ matrix.build_type }}-${{ matrix.compiler }}
